### ISSUE TITLE
Inside design guidance

### ISSUE THREAD

**Issue by adyhoran1** [DFE-Digital/design#157]
A couple of my colleagues were not clear what the difference was between an ['inside design' project page](https://design.education.gov.uk/inside-design/projects/family-hubs) and a [DfE digital blog]([DfE digital blog](https://dfedigital.blog.gov.uk/)) post

Could the [inside design guidance](https://design.education.gov.uk/content-design/writing-inside-design-page/) mention the words 'external' and 'stakeholders', as well as 'people'? 

For example, "The purpose of the page is to keep **external stakeholders** informed and offer opportunities for them to get involved through show and tells, research, or webinars. By working in the open, you can involve **external** people who may not be in your user group that are affected by your services."

Alternatives I've considered are explicitly saying why an 'inside design' page is different from a DfE digital blog - but I'm not sure there's a user need for this.

**Comment by CroftLA** [comment]
I have made the change to the page.

**Comment by adyhoran1** [comment]
Thank you @CroftLA 👍🏻
