### ISSUE TITLE
WCAG 2.2 dates

### ISSUE THREAD

**Issue by adyhoran1** [DFE-Digital/design#66]
Regarding this quote: "These are coming into force between June and September 2023 with compliance expected within 6 to 9 months after." on this page: https://design.education.gov.uk/accessibility

A colleague attended a presentation which said that WCAG 2.2 will come into force between **July** and September, and the Cabinet Office will start monitoring WCAG 2.2 **a year after it's published**. See [WCAG 2.2. slide deck](https://educationgovuk-my.sharepoint.com/:p:/g/personal/stephanie_krus_education_gov_uk/EQwDXKX2XOlOpp_b3N20ASsBegmpGb-8cDKgrKu6A6BKhw?e=L8bfa6).

Decide whether to update the design manual content to match. Andy's feedback "the shorter timescale [6 to 9 months] might make some people take more notice of it.)

**Comment by andyjones81** [comment]
Closing down. Ive updated the guidance to say the following as we may introduce compliance before 12 months. 

These are coming into force between June and September 2023 with compliance expected within 12 months.
