### ISSUE TITLE
Move DfE Frontend content

### ISSUE THREAD

**Issue by adyhoran1** [DFE-Digital/design#70]
There's some DfE Frontend content at the bottom of this page: https://design.education.gov.uk/design-system/

I believe it should sit on this page instead: https://design.education.gov.uk/design-system/dfe-frontend

**Comment by andyjones81** [comment]
@adyhoran1 I'm going to close this down as the content was drafted as part of the patterns and components working group and we have done this on purpose to highlight the importance that GOV Frontent should be used first and then DfE frontend where appropriate and that it's available to use. Any questions, feel free to reopen.

**Comment by andyjones81** [comment]
@adyhoran1 I'm going to close this down as the content was drafted as part of the patterns and components working group and we have done this on purpose to highlight the importance that GOV Frontent should be used first and then DfE frontend where appropriate and that it's available to use. Any questions, feel free to reopen.
